spring:
  application:
    name: crypto-analyzer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: market.chart.group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages:
                com.w4t3rcs.cryptoanalyzer.*
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: market.chart.topic